CREATE DATABASE IF NOT EXISTS LAB_MYSQL;
USE LAB_MYSQL;

CREATE TABLE CUSTOMERS(
`CUST_ID` int NOT NULL auto_increment,
`NAME` varchar(20),
`PHONE_NUMBER` char(20),
`EMAIL` VARCHAR(255),
`CITY` VARCHAR(20),
`ADDRESS` VARCHAR(255),
`COUNTRY` VARCHAR(60),
`STATE` VARCHAR(105),
`POSTAL_CODE` VARCHAR(16),
PRIMARY KEY (`CUST_ID`)
);

SELECT *
FROM CUSTOMERS;

CREATE TABLE salespersons (
  `staff_id` int NOT NULL auto_increment,
  `name` varchar (20),
  `store` char (4),
  PRIMARY KEY (`staff_id`)
);

SELECT *
FROM SALESPERSONS;

DROP TABLE IF EXISTS CARS;
CREATE TABLE CARS (
	`CAR_ID` INT NOT NULL AUTO_INCREMENT,
	`VIN` CHAR(17),
	`MANUFACTURER` VARCHAR(30),
	`COLOR` VARCHAR (20),
	`YEAR` SMALLINT(4),
	`MODEL` VARCHAR(20),
	PRIMARY KEY (`CAR_ID`)
);

SELECT * 
FROM CARS;

 CREATE TABLE INVOICES (
	`INVOICE_NUM` int not null auto_increment,
    `CAR_ID` INT,
    `CUST_ID` int,
    `STAFF_ID` INT,
    `DATE` DATETIME,
    PRIMARY KEY (`INVOICE_NUM`),
    CONSTRAINT `CAR_REF` FOREIGN KEY (`CAR_ID`) REFERENCES `CARS`(`CAR_ID`),
    CONSTRAINT `STAFF_REF` FOREIGN KEY (`STAFF_ID`) REFERENCES `SALESPERSONS`(`STAFF_ID`)

    );
    
SELECT *
FROM INVOICES;

ALTER TABLE INVOICES
MODIFY DATE DATE;

SELECT * 
FROM SALESPERSONS;

ALTER TABLE SALESPERSONS
MODIFY STORE VARCHAR(20);
