SELECT *
FROM CUSTOMERS;

UPDATE CUSTOMERS
SET EMAIL="ppicasso@gmail.com"
WHERE CUST_ID="10001";

UPDATE CUSTOMERS
SET EMAIL="lincoln@us.gov"
WHERE CUST_ID="20001";

UPDATE CUSTOMERS
SET EMAIL="hello@napoleon.me"
WHERE CUST_ID="30001";